name: CI RSpec Tests

on: push

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.0'
      - name: Check Ruby version
        run: |
          ruby -v
      - name: Run bundle install
        run: |
            gem install bundler
            bundle install
      - name: Run rspec
        run: bundle exec rspec spec
